[
  {
    type: "directory",
    name: "files/en-us/web/css",
    contents: [
      { type: "directory", name: "--_star_" },
      { type: "directory", name: "-moz-float-edge" },
      { type: "directory", name: "-moz-force-broken-image-icon" },
      { type: "directory", name: "-moz-image-rect" },
      { type: "directory", name: "-moz-image-region" },
      { type: "directory", name: "-moz-orient" },
      { type: "directory", name: "-moz-user-focus" },
      { type: "directory", name: "-moz-user-input" },
      { type: "directory", name: "-webkit-border-before" },
      { type: "directory", name: "-webkit-box-reflect" },
      { type: "directory", name: "-webkit-mask-box-image" },
      { type: "directory", name: "-webkit-mask-composite" },
      { type: "directory", name: "-webkit-mask-position-x" },
      { type: "directory", name: "-webkit-mask-position-y" },
      { type: "directory", name: "-webkit-mask-repeat-x" },
      { type: "directory", name: "-webkit-mask-repeat-y" },
      { type: "directory", name: "-webkit-tap-highlight-color" },
      { type: "directory", name: "-webkit-text-fill-color" },
      { type: "directory", name: "-webkit-text-security" },
      { type: "directory", name: "-webkit-text-stroke" },
      { type: "directory", name: "-webkit-text-stroke-color" },
      { type: "directory", name: "-webkit-text-stroke-width" },
      { type: "directory", name: "-webkit-touch-callout" },
      { type: "directory", name: "@charset" },
      { type: "directory", name: "@color-profile" },
      { type: "directory", name: "@container" },
      {
        type: "directory",
        name: "@counter-style",
        contents: [
          { type: "directory", name: "additive-symbols" },
          { type: "directory", name: "fallback" },
          { type: "directory", name: "negative" },
          { type: "directory", name: "pad" },
          { type: "directory", name: "prefix" },
          { type: "directory", name: "range" },
          { type: "directory", name: "speak-as" },
          { type: "directory", name: "suffix" },
          { type: "directory", name: "symbols" },
          { type: "directory", name: "system" },
        ],
      },
      { type: "directory", name: "@document" },
      {
        type: "directory",
        name: "@font-face",
        contents: [
          { type: "directory", name: "ascent-override" },
          { type: "directory", name: "descent-override" },
          { type: "directory", name: "font-display" },
          { type: "directory", name: "font-family" },
          { type: "directory", name: "font-feature-settings" },
          { type: "directory", name: "font-stretch" },
          { type: "directory", name: "font-style" },
          { type: "directory", name: "font-variation-settings" },
          { type: "directory", name: "font-weight" },
          { type: "directory", name: "line-gap-override" },
          { type: "directory", name: "size-adjust" },
          { type: "directory", name: "src" },
          { type: "directory", name: "unicode-range" },
        ],
      },
      {
        type: "directory",
        name: "@font-feature-values",
        contents: [{ type: "directory", name: "font-display" }],
      },
      {
        type: "directory",
        name: "@font-palette-values",
        contents: [
          { type: "directory", name: "base-palette" },
          { type: "directory", name: "font-family" },
          { type: "directory", name: "override-colors" },
        ],
      },
      {
        type: "directory",
        name: "@import",
        contents: [{ type: "directory", name: "layer_function" }],
      },
      { type: "directory", name: "@keyframes" },
      { type: "directory", name: "@layer" },
      {
        type: "directory",
        name: "@media",
        contents: [
          { type: "directory", name: "-moz-device-pixel-ratio" },
          { type: "directory", name: "-webkit-animation" },
          { type: "directory", name: "-webkit-device-pixel-ratio" },
          { type: "directory", name: "-webkit-transform-2d" },
          { type: "directory", name: "-webkit-transform-3d" },
          { type: "directory", name: "-webkit-transition" },
          { type: "directory", name: "any-hover" },
          { type: "directory", name: "any-pointer" },
          { type: "directory", name: "aspect-ratio" },
          { type: "directory", name: "aural" },
          { type: "directory", name: "color" },
          { type: "directory", name: "color-gamut" },
          { type: "directory", name: "color-index" },
          { type: "directory", name: "device-aspect-ratio" },
          { type: "directory", name: "device-height" },
          { type: "directory", name: "device-posture" },
          { type: "directory", name: "device-width" },
          { type: "directory", name: "display-mode" },
          { type: "directory", name: "dynamic-range" },
          { type: "directory", name: "forced-colors" },
          { type: "directory", name: "grid" },
          { type: "directory", name: "height" },
          { type: "directory", name: "hover" },
          { type: "directory", name: "inverted-colors" },
          { type: "directory", name: "monochrome" },
          { type: "directory", name: "orientation" },
          { type: "directory", name: "overflow-block" },
          { type: "directory", name: "overflow-inline" },
          { type: "directory", name: "pointer" },
          { type: "directory", name: "prefers-color-scheme" },
          { type: "directory", name: "prefers-contrast" },
          { type: "directory", name: "prefers-reduced-data" },
          { type: "directory", name: "prefers-reduced-motion" },
          { type: "directory", name: "prefers-reduced-transparency" },
          { type: "directory", name: "resolution" },
          { type: "directory", name: "scan" },
          { type: "directory", name: "scripting" },
          { type: "directory", name: "shape" },
          { type: "directory", name: "update" },
          { type: "directory", name: "video-dynamic-range" },
          { type: "directory", name: "width" },
        ],
      },
      { type: "directory", name: "@namespace" },
      {
        type: "directory",
        name: "@page",
        contents: [
          { type: "directory", name: "page-orientation" },
          { type: "directory", name: "size" },
        ],
      },
      { type: "directory", name: "@position-try" },
      {
        type: "directory",
        name: "@property",
        contents: [
          { type: "directory", name: "inherits" },
          { type: "directory", name: "initial-value" },
          { type: "directory", name: "syntax" },
        ],
      },
      { type: "directory", name: "@scope" },
      { type: "directory", name: "@starting-style" },
      { type: "directory", name: "@supports" },
      { type: "directory", name: "@view-transition" },
      { type: "directory", name: "_colon_-moz-broken" },
      { type: "directory", name: "_colon_-moz-drag-over" },
      { type: "directory", name: "_colon_-moz-first-node" },
      { type: "directory", name: "_colon_-moz-handler-blocked" },
      { type: "directory", name: "_colon_-moz-handler-crashed" },
      { type: "directory", name: "_colon_-moz-handler-disabled" },
      { type: "directory", name: "_colon_-moz-last-node" },
      { type: "directory", name: "_colon_-moz-loading" },
      { type: "directory", name: "_colon_-moz-locale-dir_ltr" },
      { type: "directory", name: "_colon_-moz-locale-dir_rtl" },
      { type: "directory", name: "_colon_-moz-only-whitespace" },
      { type: "directory", name: "_colon_-moz-submit-invalid" },
      { type: "directory", name: "_colon_-moz-suppressed" },
      { type: "directory", name: "_colon_-moz-user-disabled" },
      { type: "directory", name: "_colon_-moz-window-inactive" },
      { type: "directory", name: "_colon_active" },
      { type: "directory", name: "_colon_any-link" },
      { type: "directory", name: "_colon_autofill" },
      { type: "directory", name: "_colon_blank" },
      { type: "directory", name: "_colon_buffering" },
      { type: "directory", name: "_colon_checked" },
      { type: "directory", name: "_colon_current" },
      { type: "directory", name: "_colon_default" },
      { type: "directory", name: "_colon_defined" },
      { type: "directory", name: "_colon_dir" },
      { type: "directory", name: "_colon_disabled" },
      { type: "directory", name: "_colon_empty" },
      { type: "directory", name: "_colon_enabled" },
      { type: "directory", name: "_colon_first" },
      { type: "directory", name: "_colon_first-child" },
      { type: "directory", name: "_colon_first-of-type" },
      { type: "directory", name: "_colon_focus" },
      { type: "directory", name: "_colon_focus-visible" },
      { type: "directory", name: "_colon_focus-within" },
      { type: "directory", name: "_colon_fullscreen" },
      { type: "directory", name: "_colon_future" },
      { type: "directory", name: "_colon_has" },
      { type: "directory", name: "_colon_has-slotted" },
      { type: "directory", name: "_colon_host" },
      { type: "directory", name: "_colon_host-context" },
      { type: "directory", name: "_colon_host_function" },
      { type: "directory", name: "_colon_hover" },
      { type: "directory", name: "_colon_in-range" },
      { type: "directory", name: "_colon_indeterminate" },
      { type: "directory", name: "_colon_invalid" },
      { type: "directory", name: "_colon_is" },
      { type: "directory", name: "_colon_lang" },
      { type: "directory", name: "_colon_last-child" },
      { type: "directory", name: "_colon_last-of-type" },
      { type: "directory", name: "_colon_left" },
      { type: "directory", name: "_colon_link" },
      { type: "directory", name: "_colon_local-link" },
      { type: "directory", name: "_colon_modal" },
      { type: "directory", name: "_colon_muted" },
      { type: "directory", name: "_colon_not" },
      { type: "directory", name: "_colon_nth-child" },
      { type: "directory", name: "_colon_nth-last-child" },
      { type: "directory", name: "_colon_nth-last-of-type" },
      { type: "directory", name: "_colon_nth-of-type" },
      { type: "directory", name: "_colon_only-child" },
      { type: "directory", name: "_colon_only-of-type" },
      { type: "directory", name: "_colon_open" },
      { type: "directory", name: "_colon_optional" },
      { type: "directory", name: "_colon_out-of-range" },
      { type: "directory", name: "_colon_past" },
      { type: "directory", name: "_colon_paused" },
      { type: "directory", name: "_colon_picture-in-picture" },
      { type: "directory", name: "_colon_placeholder-shown" },
      { type: "directory", name: "_colon_playing" },
      { type: "directory", name: "_colon_popover-open" },
      { type: "directory", name: "_colon_read-only" },
      { type: "directory", name: "_colon_read-write" },
      { type: "directory", name: "_colon_required" },
      { type: "directory", name: "_colon_right" },
      { type: "directory", name: "_colon_root" },
      { type: "directory", name: "_colon_scope" },
      { type: "directory", name: "_colon_seeking" },
      { type: "directory", name: "_colon_stalled" },
      { type: "directory", name: "_colon_state" },
      { type: "directory", name: "_colon_target" },
      { type: "directory", name: "_colon_target-current" },
      { type: "directory", name: "_colon_target-within" },
      { type: "directory", name: "_colon_user-invalid" },
      { type: "directory", name: "_colon_user-valid" },
      { type: "directory", name: "_colon_valid" },
      { type: "directory", name: "_colon_visited" },
      { type: "directory", name: "_colon_volume-locked" },
      { type: "directory", name: "_colon_where" },
      { type: "directory", name: "_doublecolon_-moz-color-swatch" },
      { type: "directory", name: "_doublecolon_-moz-focus-inner" },
      { type: "directory", name: "_doublecolon_-moz-list-bullet" },
      { type: "directory", name: "_doublecolon_-moz-list-number" },
      { type: "directory", name: "_doublecolon_-moz-meter-bar" },
      { type: "directory", name: "_doublecolon_-moz-progress-bar" },
      { type: "directory", name: "_doublecolon_-moz-range-progress" },
      { type: "directory", name: "_doublecolon_-moz-range-thumb" },
      { type: "directory", name: "_doublecolon_-moz-range-track" },
      { type: "directory", name: "_doublecolon_-webkit-inner-spin-button" },
      { type: "directory", name: "_doublecolon_-webkit-meter-bar" },
      {
        type: "directory",
        name: "_doublecolon_-webkit-meter-even-less-good-value",
      },
      { type: "directory", name: "_doublecolon_-webkit-meter-inner-element" },
      { type: "directory", name: "_doublecolon_-webkit-meter-optimum-value" },
      {
        type: "directory",
        name: "_doublecolon_-webkit-meter-suboptimum-value",
      },
      { type: "directory", name: "_doublecolon_-webkit-progress-bar" },
      {
        type: "directory",
        name: "_doublecolon_-webkit-progress-inner-element",
      },
      { type: "directory", name: "_doublecolon_-webkit-progress-value" },
      { type: "directory", name: "_doublecolon_-webkit-scrollbar" },
      { type: "directory", name: "_doublecolon_-webkit-search-cancel-button" },
      { type: "directory", name: "_doublecolon_-webkit-search-results-button" },
      { type: "directory", name: "_doublecolon_-webkit-slider-runnable-track" },
      { type: "directory", name: "_doublecolon_-webkit-slider-thumb" },
      { type: "directory", name: "_doublecolon_after" },
      { type: "directory", name: "_doublecolon_backdrop" },
      { type: "directory", name: "_doublecolon_before" },
      { type: "directory", name: "_doublecolon_checkmark" },
      { type: "directory", name: "_doublecolon_column" },
      { type: "directory", name: "_doublecolon_cue" },
      { type: "directory", name: "_doublecolon_details-content" },
      { type: "directory", name: "_doublecolon_file-selector-button" },
      { type: "directory", name: "_doublecolon_first-letter" },
      { type: "directory", name: "_doublecolon_first-line" },
      { type: "directory", name: "_doublecolon_grammar-error" },
      { type: "directory", name: "_doublecolon_highlight" },
      { type: "directory", name: "_doublecolon_marker" },
      { type: "directory", name: "_doublecolon_part" },
      { type: "directory", name: "_doublecolon_picker" },
      { type: "directory", name: "_doublecolon_picker-icon" },
      { type: "directory", name: "_doublecolon_placeholder" },
      { type: "directory", name: "_doublecolon_scroll-button" },
      { type: "directory", name: "_doublecolon_scroll-marker" },
      { type: "directory", name: "_doublecolon_scroll-marker-group" },
      { type: "directory", name: "_doublecolon_selection" },
      { type: "directory", name: "_doublecolon_slotted" },
      { type: "directory", name: "_doublecolon_spelling-error" },
      { type: "directory", name: "_doublecolon_target-text" },
      { type: "directory", name: "_doublecolon_view-transition" },
      { type: "directory", name: "_doublecolon_view-transition-group" },
      { type: "directory", name: "_doublecolon_view-transition-image-pair" },
      { type: "directory", name: "_doublecolon_view-transition-new" },
      { type: "directory", name: "_doublecolon_view-transition-old" },
      { type: "directory", name: "abs" },
      { type: "directory", name: "absolute-size" },
      { type: "directory", name: "accent-color" },
      { type: "directory", name: "acos" },
      { type: "directory", name: "align-content" },
      { type: "directory", name: "align-items" },
      { type: "directory", name: "align-self" },
      { type: "directory", name: "alignment-baseline" },
      { type: "directory", name: "all" },
      { type: "directory", name: "alpha-value" },
      { type: "directory", name: "anchor" },
      { type: "directory", name: "anchor-name" },
      { type: "directory", name: "anchor-size" },
      { type: "directory", name: "angle" },
      { type: "directory", name: "angle-percentage" },
      { type: "directory", name: "animation" },
      { type: "directory", name: "animation-composition" },
      { type: "directory", name: "animation-delay" },
      { type: "directory", name: "animation-direction" },
      { type: "directory", name: "animation-duration" },
      { type: "directory", name: "animation-fill-mode" },
      { type: "directory", name: "animation-iteration-count" },
      { type: "directory", name: "animation-name" },
      { type: "directory", name: "animation-play-state" },
      { type: "directory", name: "animation-range" },
      { type: "directory", name: "animation-range-end" },
      { type: "directory", name: "animation-range-start" },
      {
        type: "directory",
        name: "animation-timeline",
        contents: [
          { type: "directory", name: "scroll" },
          { type: "directory", name: "view" },
        ],
      },
      { type: "directory", name: "animation-timing-function" },
      { type: "directory", name: "appearance" },
      { type: "directory", name: "asin" },
      { type: "directory", name: "aspect-ratio" },
      { type: "directory", name: "atan" },
      { type: "directory", name: "atan2" },
      { type: "directory", name: "attr" },
      { type: "directory", name: "attribute_selectors" },
      { type: "directory", name: "backdrop-filter" },
      { type: "directory", name: "backface-visibility" },
      { type: "directory", name: "background" },
      { type: "directory", name: "background-attachment" },
      { type: "directory", name: "background-blend-mode" },
      { type: "directory", name: "background-clip" },
      { type: "directory", name: "background-color" },
      { type: "directory", name: "background-image" },
      { type: "directory", name: "background-origin" },
      { type: "directory", name: "background-position" },
      { type: "directory", name: "background-position-x" },
      { type: "directory", name: "background-position-y" },
      { type: "directory", name: "background-repeat" },
      { type: "directory", name: "background-size" },
      { type: "directory", name: "baseline-position" },
      {
        type: "directory",
        name: "basic-shape",
        contents: [
          { type: "directory", name: "circle" },
          { type: "directory", name: "ellipse" },
          { type: "directory", name: "inset" },
          { type: "directory", name: "path" },
          { type: "directory", name: "polygon" },
          { type: "directory", name: "rect" },
          { type: "directory", name: "shape" },
          { type: "directory", name: "xywh" },
        ],
      },
      { type: "directory", name: "blend-mode" },
      { type: "directory", name: "block-size" },
      { type: "directory", name: "border" },
      { type: "directory", name: "border-block" },
      { type: "directory", name: "border-block-color" },
      { type: "directory", name: "border-block-end" },
      { type: "directory", name: "border-block-end-color" },
      { type: "directory", name: "border-block-end-style" },
      { type: "directory", name: "border-block-end-width" },
      { type: "directory", name: "border-block-start" },
      { type: "directory", name: "border-block-start-color" },
      { type: "directory", name: "border-block-start-style" },
      { type: "directory", name: "border-block-start-width" },
      { type: "directory", name: "border-block-style" },
      { type: "directory", name: "border-block-width" },
      { type: "directory", name: "border-bottom" },
      { type: "directory", name: "border-bottom-color" },
      { type: "directory", name: "border-bottom-left-radius" },
      { type: "directory", name: "border-bottom-right-radius" },
      { type: "directory", name: "border-bottom-style" },
      { type: "directory", name: "border-bottom-width" },
      { type: "directory", name: "border-collapse" },
      { type: "directory", name: "border-color" },
      { type: "directory", name: "border-end-end-radius" },
      { type: "directory", name: "border-end-start-radius" },
      { type: "directory", name: "border-image" },
      { type: "directory", name: "border-image-outset" },
      { type: "directory", name: "border-image-repeat" },
      { type: "directory", name: "border-image-slice" },
      { type: "directory", name: "border-image-source" },
      { type: "directory", name: "border-image-width" },
      { type: "directory", name: "border-inline" },
      { type: "directory", name: "border-inline-color" },
      { type: "directory", name: "border-inline-end" },
      { type: "directory", name: "border-inline-end-color" },
      { type: "directory", name: "border-inline-end-style" },
      { type: "directory", name: "border-inline-end-width" },
      { type: "directory", name: "border-inline-start" },
      { type: "directory", name: "border-inline-start-color" },
      { type: "directory", name: "border-inline-start-style" },
      { type: "directory", name: "border-inline-start-width" },
      { type: "directory", name: "border-inline-style" },
      { type: "directory", name: "border-inline-width" },
      { type: "directory", name: "border-left" },
      { type: "directory", name: "border-left-color" },
      { type: "directory", name: "border-left-style" },
      { type: "directory", name: "border-left-width" },
      { type: "directory", name: "border-radius" },
      { type: "directory", name: "border-right" },
      { type: "directory", name: "border-right-color" },
      { type: "directory", name: "border-right-style" },
      { type: "directory", name: "border-right-width" },
      { type: "directory", name: "border-spacing" },
      { type: "directory", name: "border-start-end-radius" },
      { type: "directory", name: "border-start-start-radius" },
      { type: "directory", name: "border-style" },
      { type: "directory", name: "border-top" },
      { type: "directory", name: "border-top-color" },
      { type: "directory", name: "border-top-left-radius" },
      { type: "directory", name: "border-top-right-radius" },
      { type: "directory", name: "border-top-style" },
      { type: "directory", name: "border-top-width" },
      { type: "directory", name: "border-width" },
      { type: "directory", name: "bottom" },
      { type: "directory", name: "box-align" },
      { type: "directory", name: "box-decoration-break" },
      { type: "directory", name: "box-direction" },
      { type: "directory", name: "box-edge" },
      { type: "directory", name: "box-flex" },
      { type: "directory", name: "box-flex-group" },
      { type: "directory", name: "box-lines" },
      { type: "directory", name: "box-ordinal-group" },
      { type: "directory", name: "box-orient" },
      { type: "directory", name: "box-pack" },
      { type: "directory", name: "box-shadow" },
      { type: "directory", name: "box-sizing" },
      { type: "directory", name: "break-after" },
      { type: "directory", name: "break-before" },
      { type: "directory", name: "break-inside" },
      { type: "directory", name: "calc" },
      { type: "directory", name: "calc-keyword" },
      { type: "directory", name: "calc-size" },
      { type: "directory", name: "calc-sum" },
      { type: "directory", name: "caption-side" },
      { type: "directory", name: "caret-color" },
      { type: "directory", name: "child_combinator" },
      { type: "directory", name: "clamp" },
      { type: "directory", name: "class_selectors" },
      { type: "directory", name: "clear" },
      { type: "directory", name: "clip" },
      { type: "directory", name: "clip-path" },
      { type: "directory", name: "clip-rule" },
      { type: "directory", name: "color" },
      { type: "directory", name: "color-interpolation" },
      { type: "directory", name: "color-interpolation-filters" },
      { type: "directory", name: "color-interpolation-method" },
      { type: "directory", name: "color-scheme" },
      {
        type: "directory",
        name: "color_value",
        contents: [
          { type: "directory", name: "color" },
          { type: "directory", name: "color-mix" },
          { type: "directory", name: "device-cmyk" },
          { type: "directory", name: "hsl" },
          { type: "directory", name: "hwb" },
          { type: "directory", name: "lab" },
          { type: "directory", name: "lch" },
          { type: "directory", name: "light-dark" },
          { type: "directory", name: "oklab" },
          { type: "directory", name: "oklch" },
          { type: "directory", name: "rgb" },
        ],
      },
      { type: "directory", name: "column-count" },
      { type: "directory", name: "column-fill" },
      { type: "directory", name: "column-gap" },
      { type: "directory", name: "column-rule" },
      { type: "directory", name: "column-rule-color" },
      { type: "directory", name: "column-rule-style" },
      { type: "directory", name: "column-rule-width" },
      { type: "directory", name: "column-span" },
      { type: "directory", name: "column-width" },
      { type: "directory", name: "column_combinator" },
      { type: "directory", name: "columns" },
      { type: "directory", name: "contain" },
      { type: "directory", name: "contain-intrinsic-block-size" },
      { type: "directory", name: "contain-intrinsic-height" },
      { type: "directory", name: "contain-intrinsic-inline-size" },
      { type: "directory", name: "contain-intrinsic-size" },
      { type: "directory", name: "contain-intrinsic-width" },
      { type: "directory", name: "container" },
      { type: "directory", name: "container-name" },
      { type: "directory", name: "container-type" },
      { type: "directory", name: "content" },
      { type: "directory", name: "content-distribution" },
      { type: "directory", name: "content-position" },
      { type: "directory", name: "content-visibility" },
      { type: "directory", name: "cos" },
      { type: "directory", name: "counter" },
      { type: "directory", name: "counter-increment" },
      { type: "directory", name: "counter-reset" },
      { type: "directory", name: "counter-set" },
      { type: "directory", name: "counters" },
      { type: "directory", name: "cross-fade" },
      {
        type: "directory",
        name: "css_anchor_positioning",
        contents: [
          { type: "directory", name: "try_options_hiding" },
          { type: "directory", name: "using" },
        ],
      },
      { type: "directory", name: "css_animated_properties" },
      {
        type: "directory",
        name: "css_animations",
        contents: [{ type: "directory", name: "using_css_animations" }],
      },
      {
        type: "directory",
        name: "css_backgrounds_and_borders",
        contents: [
          { type: "directory", name: "border-image_generator" },
          { type: "directory", name: "border-radius_generator" },
          { type: "directory", name: "box-shadow_generator" },
          { type: "directory", name: "resizing_background_images" },
          { type: "directory", name: "scaling_of_svg_backgrounds" },
          { type: "directory", name: "using_multiple_backgrounds" },
        ],
      },
      { type: "directory", name: "css_basic_user_interface" },
      {
        type: "directory",
        name: "css_box_alignment",
        contents: [
          { type: "directory", name: "box_alignment" },
          { type: "directory", name: "box_alignment_in_block_abspos_tables" },
          { type: "directory", name: "box_alignment_in_flexbox" },
          { type: "directory", name: "box_alignment_in_grid_layout" },
          { type: "directory", name: "box_alignment_in_multi-column_layout" },
        ],
      },
      {
        type: "directory",
        name: "css_box_model",
        contents: [
          { type: "directory", name: "introduction_to_the_css_box_model" },
          { type: "directory", name: "mastering_margin_collapsing" },
        ],
      },
      {
        type: "directory",
        name: "css_box_sizing",
        contents: [{ type: "directory", name: "understanding_aspect-ratio" }],
      },
      {
        type: "directory",
        name: "css_cascade",
        contents: [
          { type: "directory", name: "cascade" },
          { type: "directory", name: "inheritance" },
          { type: "directory", name: "shorthand_properties" },
          { type: "directory", name: "specificity" },
          { type: "directory", name: "value_processing" },
        ],
      },
      {
        type: "directory",
        name: "css_cascading_variables",
        contents: [{ type: "directory", name: "using_css_custom_properties" }],
      },
      { type: "directory", name: "css_color_adjustment" },
      {
        type: "directory",
        name: "css_colors",
        contents: [
          { type: "directory", name: "applying_color" },
          { type: "directory", name: "color_picker_tool" },
          { type: "directory", name: "color_values" },
          { type: "directory", name: "relative_colors" },
          { type: "directory", name: "using_color_wisely" },
        ],
      },
      { type: "directory", name: "css_compositing_and_blending" },
      {
        type: "directory",
        name: "css_conditional_rules",
        contents: [
          { type: "directory", name: "container_scroll-state_queries" },
          { type: "directory", name: "using_feature_queries" },
        ],
      },
      {
        type: "directory",
        name: "css_containment",
        contents: [
          { type: "directory", name: "container_queries" },
          { type: "directory", name: "container_size_and_style_queries" },
          { type: "directory", name: "using_css_containment" },
        ],
      },
      {
        type: "directory",
        name: "css_counter_styles",
        contents: [{ type: "directory", name: "using_css_counters" }],
      },
      {
        type: "directory",
        name: "css_display",
        contents: [
          { type: "directory", name: "block_and_inline_layout_in_normal_flow" },
          { type: "directory", name: "block_formatting_context" },
          { type: "directory", name: "containing_block" },
          { type: "directory", name: "flow_layout" },
          { type: "directory", name: "flow_layout_and_overflow" },
          { type: "directory", name: "flow_layout_and_writing_modes" },
          { type: "directory", name: "in_flow_and_out_of_flow" },
          { type: "directory", name: "introduction_to_formatting_contexts" },
          { type: "directory", name: "multi-keyword_syntax_of_display" },
          { type: "directory", name: "visual_formatting_model" },
        ],
      },
      {
        type: "directory",
        name: "css_filter_effects",
        contents: [{ type: "directory", name: "using_filter_effects" }],
      },
      {
        type: "directory",
        name: "css_flexible_box_layout",
        contents: [
          { type: "directory", name: "aligning_items_in_a_flex_container" },
          { type: "directory", name: "basic_concepts_of_flexbox" },
          {
            type: "directory",
            name: "controlling_ratios_of_flex_items_along_the_main_axis",
          },
          { type: "directory", name: "mastering_wrapping_of_flex_items" },
          { type: "directory", name: "ordering_flex_items" },
          {
            type: "directory",
            name: "relationship_of_flexbox_to_other_layout_methods",
          },
          { type: "directory", name: "typical_use_cases_of_flexbox" },
        ],
      },
      { type: "directory", name: "css_font_loading" },
      {
        type: "directory",
        name: "css_fonts",
        contents: [
          { type: "directory", name: "opentype_fonts_guide" },
          { type: "directory", name: "variable_fonts_guide" },
          { type: "directory", name: "woff" },
        ],
      },
      { type: "directory", name: "css_fragmentation" },
      { type: "directory", name: "css_generated_content" },
      {
        type: "directory",
        name: "css_grid_layout",
        contents: [
          { type: "directory", name: "auto-placement_in_grid_layout" },
          { type: "directory", name: "basic_concepts_of_grid_layout" },
          { type: "directory", name: "box_alignment_in_grid_layout" },
          { type: "directory", name: "grid_layout_and_accessibility" },
          {
            type: "directory",
            name: "grid_layout_and_progressive_enhancement",
          },
          { type: "directory", name: "grid_layout_using_line-based_placement" },
          { type: "directory", name: "grid_layout_using_named_grid_lines" },
          { type: "directory", name: "grid_template_areas" },
          { type: "directory", name: "grids_logical_values_and_writing_modes" },
          { type: "directory", name: "masonry_layout" },
          { type: "directory", name: "realizing_common_layouts_using_grids" },
          {
            type: "directory",
            name: "relationship_of_grid_layout_with_other_layout_methods",
          },
          { type: "directory", name: "subgrid" },
        ],
      },
      {
        type: "directory",
        name: "css_images",
        contents: [
          { type: "directory", name: "implementing_image_sprites_in_css" },
          { type: "directory", name: "replaced_element_properties" },
          { type: "directory", name: "using_css_gradients" },
        ],
      },
      {
        type: "directory",
        name: "css_inline_layout",
        contents: [{ type: "directory", name: "inline_formatting_context" }],
      },
      {
        type: "directory",
        name: "css_lists",
        contents: [{ type: "directory", name: "consistent_list_indentation" }],
      },
      {
        type: "directory",
        name: "css_logical_properties_and_values",
        contents: [
          {
            type: "directory",
            name: "basic_concepts_of_logical_properties_and_values",
          },
          { type: "directory", name: "floating_and_positioning" },
          { type: "directory", name: "margins_borders_padding" },
          { type: "directory", name: "sizing" },
        ],
      },
      { type: "directory", name: "css_masking" },
      {
        type: "directory",
        name: "css_media_queries",
        contents: [
          { type: "directory", name: "printing" },
          { type: "directory", name: "testing_media_queries" },
          { type: "directory", name: "using_media_queries" },
          { type: "directory", name: "using_media_queries_for_accessibility" },
        ],
      },
      { type: "directory", name: "css_motion_path" },
      {
        type: "directory",
        name: "css_multicol_layout",
        contents: [
          { type: "directory", name: "basic_concepts" },
          {
            type: "directory",
            name: "handling_content_breaks_in_multicol_layout",
          },
          { type: "directory", name: "handling_overflow_in_multicol_layout" },
          { type: "directory", name: "spanning_balancing_columns" },
          { type: "directory", name: "styling_columns" },
          { type: "directory", name: "using_multicol_layouts" },
        ],
      },
      { type: "directory", name: "css_namespaces" },
      {
        type: "directory",
        name: "css_nesting",
        contents: [
          { type: "directory", name: "nesting_and_specificity" },
          { type: "directory", name: "nesting_at-rules" },
          { type: "directory", name: "using_css_nesting" },
        ],
      },
      {
        type: "directory",
        name: "css_overflow",
        contents: [{ type: "directory", name: "css_carousels" }],
      },
      { type: "directory", name: "css_overscroll_behavior" },
      { type: "directory", name: "css_paged_media" },
      {
        type: "directory",
        name: "css_positioned_layout",
        contents: [
          {
            type: "directory",
            name: "stacking_context",
            contents: [
              { type: "directory", name: "stacking_context_example_1" },
              { type: "directory", name: "stacking_context_example_2" },
              { type: "directory", name: "stacking_context_example_3" },
            ],
          },
          { type: "directory", name: "stacking_floating_elements" },
          { type: "directory", name: "stacking_without_z-index" },
          { type: "directory", name: "understanding_z-index" },
          { type: "directory", name: "using_z-index" },
        ],
      },
      {
        type: "directory",
        name: "css_properties_and_values_api",
        contents: [{ type: "directory", name: "houdini" }],
      },
      { type: "directory", name: "css_pseudo-elements" },
      { type: "directory", name: "css_ruby_layout" },
      { type: "directory", name: "css_scoping" },
      { type: "directory", name: "css_scroll-driven_animations" },
      {
        type: "directory",
        name: "css_scroll_anchoring",
        contents: [{ type: "directory", name: "scroll_anchoring" }],
      },
      {
        type: "directory",
        name: "css_scroll_snap",
        contents: [
          { type: "directory", name: "basic_concepts" },
          { type: "directory", name: "using_scroll_snap_events" },
        ],
      },
      { type: "directory", name: "css_scrollbars_styling" },
      {
        type: "directory",
        name: "css_selectors",
        contents: [
          { type: "directory", name: "privacy_and_the_visited_selector" },
          { type: "directory", name: "selector_structure" },
          { type: "directory", name: "selectors_and_combinators" },
          {
            type: "directory",
            name: "using_the__colon_target_pseudo-class_in_selectors",
          },
        ],
      },
      { type: "directory", name: "css_shadow_parts" },
      {
        type: "directory",
        name: "css_shapes",
        contents: [
          { type: "directory", name: "basic_shapes" },
          { type: "directory", name: "from_box_values" },
          { type: "directory", name: "overview_of_shapes" },
          { type: "directory", name: "shapes_from_images" },
        ],
      },
      {
        type: "directory",
        name: "css_syntax",
        contents: [
          { type: "directory", name: "at-rule" },
          { type: "directory", name: "at-rule_functions" },
          { type: "directory", name: "comments" },
          { type: "directory", name: "error_handling" },
          { type: "directory", name: "syntax" },
        ],
      },
      { type: "directory", name: "css_table" },
      {
        type: "directory",
        name: "css_text",
        contents: [{ type: "directory", name: "wrapping_breaking_text" }],
      },
      { type: "directory", name: "css_text_decoration" },
      {
        type: "directory",
        name: "css_transforms",
        contents: [{ type: "directory", name: "using_css_transforms" }],
      },
      {
        type: "directory",
        name: "css_transitions",
        contents: [{ type: "directory", name: "using_css_transitions" }],
      },
      {
        type: "directory",
        name: "css_values_and_units",
        contents: [
          { type: "directory", name: "css_data_types" },
          { type: "directory", name: "css_value_functions" },
          { type: "directory", name: "numeric_data_types" },
          { type: "directory", name: "textual_data_types" },
          { type: "directory", name: "using_css_math_functions" },
          { type: "directory", name: "value_definition_syntax" },
        ],
      },
      { type: "directory", name: "css_view_transitions" },
      {
        type: "directory",
        name: "css_writing_modes",
        contents: [{ type: "directory", name: "vertical_controls" }],
      },
      {
        type: "directory",
        name: "cssom_view",
        contents: [
          { type: "directory", name: "coordinate_systems" },
          { type: "directory", name: "viewport_concepts" },
        ],
      },
      { type: "directory", name: "cursor" },
      { type: "directory", name: "custom-ident" },
      { type: "directory", name: "cx" },
      { type: "directory", name: "cy" },
      { type: "directory", name: "d" },
      { type: "directory", name: "dashed-ident" },
      { type: "directory", name: "descendant_combinator" },
      { type: "directory", name: "dimension" },
      { type: "directory", name: "direction" },
      { type: "directory", name: "display" },
      { type: "directory", name: "display-box" },
      { type: "directory", name: "display-inside" },
      { type: "directory", name: "display-internal" },
      { type: "directory", name: "display-legacy" },
      { type: "directory", name: "display-listitem" },
      { type: "directory", name: "display-outside" },
      { type: "directory", name: "dominant-baseline" },
      {
        type: "directory",
        name: "easing-function",
        contents: [
          { type: "directory", name: "cubic-bezier" },
          { type: "directory", name: "linear" },
          { type: "directory", name: "steps" },
        ],
      },
      { type: "directory", name: "element" },
      { type: "directory", name: "empty-cells" },
      { type: "directory", name: "env" },
      { type: "directory", name: "exp" },
      { type: "directory", name: "field-sizing" },
      { type: "directory", name: "fill" },
      { type: "directory", name: "fill-opacity" },
      { type: "directory", name: "fill-rule" },
      { type: "directory", name: "filter" },
      {
        type: "directory",
        name: "filter-function",
        contents: [
          { type: "directory", name: "blur" },
          { type: "directory", name: "brightness" },
          { type: "directory", name: "contrast" },
          { type: "directory", name: "drop-shadow" },
          { type: "directory", name: "grayscale" },
          { type: "directory", name: "hue-rotate" },
          { type: "directory", name: "invert" },
          { type: "directory", name: "opacity" },
          { type: "directory", name: "saturate" },
          { type: "directory", name: "sepia" },
        ],
      },
      { type: "directory", name: "fit-content" },
      { type: "directory", name: "fit-content_function" },
      { type: "directory", name: "flex" },
      { type: "directory", name: "flex-basis" },
      { type: "directory", name: "flex-direction" },
      { type: "directory", name: "flex-flow" },
      { type: "directory", name: "flex-grow" },
      { type: "directory", name: "flex-shrink" },
      { type: "directory", name: "flex-wrap" },
      { type: "directory", name: "flex_value" },
      { type: "directory", name: "float" },
      { type: "directory", name: "flood-color" },
      { type: "directory", name: "flood-opacity" },
      { type: "directory", name: "font" },
      { type: "directory", name: "font-family" },
      { type: "directory", name: "font-feature-settings" },
      { type: "directory", name: "font-kerning" },
      { type: "directory", name: "font-language-override" },
      { type: "directory", name: "font-optical-sizing" },
      {
        type: "directory",
        name: "font-palette",
        contents: [{ type: "directory", name: "palette-mix" }],
      },
      { type: "directory", name: "font-size" },
      { type: "directory", name: "font-size-adjust" },
      { type: "directory", name: "font-smooth" },
      { type: "directory", name: "font-stretch" },
      { type: "directory", name: "font-style" },
      { type: "directory", name: "font-synthesis" },
      { type: "directory", name: "font-synthesis-position" },
      { type: "directory", name: "font-synthesis-small-caps" },
      { type: "directory", name: "font-synthesis-style" },
      { type: "directory", name: "font-synthesis-weight" },
      { type: "directory", name: "font-variant" },
      { type: "directory", name: "font-variant-alternates" },
      { type: "directory", name: "font-variant-caps" },
      { type: "directory", name: "font-variant-east-asian" },
      { type: "directory", name: "font-variant-emoji" },
      { type: "directory", name: "font-variant-ligatures" },
      { type: "directory", name: "font-variant-numeric" },
      { type: "directory", name: "font-variant-position" },
      { type: "directory", name: "font-variation-settings" },
      { type: "directory", name: "font-weight" },
      { type: "directory", name: "forced-color-adjust" },
      { type: "directory", name: "frequency" },
      { type: "directory", name: "frequency-percentage" },
      { type: "directory", name: "gap" },
      { type: "directory", name: "generic-family" },
      {
        type: "directory",
        name: "gradient",
        contents: [
          { type: "directory", name: "conic-gradient" },
          { type: "directory", name: "linear-gradient" },
          { type: "directory", name: "radial-gradient" },
          { type: "directory", name: "repeating-conic-gradient" },
          { type: "directory", name: "repeating-linear-gradient" },
          { type: "directory", name: "repeating-radial-gradient" },
        ],
      },
      { type: "directory", name: "grid" },
      { type: "directory", name: "grid-area" },
      { type: "directory", name: "grid-auto-columns" },
      { type: "directory", name: "grid-auto-flow" },
      { type: "directory", name: "grid-auto-rows" },
      { type: "directory", name: "grid-column" },
      { type: "directory", name: "grid-column-end" },
      { type: "directory", name: "grid-column-start" },
      { type: "directory", name: "grid-row" },
      { type: "directory", name: "grid-row-end" },
      { type: "directory", name: "grid-row-start" },
      { type: "directory", name: "grid-template" },
      { type: "directory", name: "grid-template-areas" },
      { type: "directory", name: "grid-template-columns" },
      { type: "directory", name: "grid-template-rows" },
      { type: "directory", name: "guides" },
      { type: "directory", name: "hanging-punctuation" },
      { type: "directory", name: "height" },
      { type: "directory", name: "hex-color" },
      { type: "directory", name: "hue" },
      { type: "directory", name: "hue-interpolation-method" },
      { type: "directory", name: "hyphenate-character" },
      { type: "directory", name: "hyphenate-limit-chars" },
      { type: "directory", name: "hyphens" },
      { type: "directory", name: "hypot" },
      { type: "directory", name: "id_selectors" },
      { type: "directory", name: "ident" },
      {
        type: "directory",
        name: "image",
        contents: [
          { type: "directory", name: "image" },
          { type: "directory", name: "image-set" },
          { type: "directory", name: "paint" },
        ],
      },
      { type: "directory", name: "image-orientation" },
      { type: "directory", name: "image-rendering" },
      { type: "directory", name: "image-resolution" },
      { type: "directory", name: "important" },
      { type: "directory", name: "inherit" },
      { type: "directory", name: "initial" },
      { type: "directory", name: "initial-letter" },
      { type: "directory", name: "inline-size" },
      { type: "directory", name: "inset" },
      { type: "directory", name: "inset-block" },
      { type: "directory", name: "inset-block-end" },
      { type: "directory", name: "inset-block-start" },
      { type: "directory", name: "inset-inline" },
      { type: "directory", name: "inset-inline-end" },
      { type: "directory", name: "inset-inline-start" },
      { type: "directory", name: "integer" },
      { type: "directory", name: "interpolate-size" },
      { type: "directory", name: "isolation" },
      { type: "directory", name: "justify-content" },
      { type: "directory", name: "justify-items" },
      { type: "directory", name: "justify-self" },
      {
        type: "directory",
        name: "layout_cookbook",
        contents: [
          { type: "directory", name: "breadcrumb_navigation" },
          { type: "directory", name: "card" },
          { type: "directory", name: "center_an_element" },
          { type: "directory", name: "column_layouts" },
          {
            type: "directory",
            name: "contribute_a_recipe",
            contents: [{ type: "directory", name: "cookbook_template" }],
          },
          { type: "directory", name: "grid_wrapper" },
          { type: "directory", name: "list_group_with_badges" },
          { type: "directory", name: "media_objects" },
          { type: "directory", name: "pagination" },
          { type: "directory", name: "split_navigation" },
          { type: "directory", name: "sticky_footers" },
        ],
      },
      { type: "directory", name: "left" },
      { type: "directory", name: "length" },
      { type: "directory", name: "length-percentage" },
      { type: "directory", name: "letter-spacing" },
      { type: "directory", name: "lighting-color" },
      { type: "directory", name: "line-break" },
      { type: "directory", name: "line-clamp" },
      { type: "directory", name: "line-height" },
      { type: "directory", name: "line-height-step" },
      { type: "directory", name: "line-style" },
      { type: "directory", name: "list-style" },
      { type: "directory", name: "list-style-image" },
      { type: "directory", name: "list-style-position" },
      { type: "directory", name: "list-style-type" },
      { type: "directory", name: "log" },
      { type: "directory", name: "margin" },
      { type: "directory", name: "margin-block" },
      { type: "directory", name: "margin-block-end" },
      { type: "directory", name: "margin-block-start" },
      { type: "directory", name: "margin-bottom" },
      { type: "directory", name: "margin-inline" },
      { type: "directory", name: "margin-inline-end" },
      { type: "directory", name: "margin-inline-start" },
      { type: "directory", name: "margin-left" },
      { type: "directory", name: "margin-right" },
      { type: "directory", name: "margin-top" },
      { type: "directory", name: "margin-trim" },
      { type: "directory", name: "marker" },
      { type: "directory", name: "marker-end" },
      { type: "directory", name: "marker-mid" },
      { type: "directory", name: "marker-start" },
      { type: "directory", name: "mask" },
      { type: "directory", name: "mask-border" },
      { type: "directory", name: "mask-border-mode" },
      { type: "directory", name: "mask-border-outset" },
      { type: "directory", name: "mask-border-repeat" },
      { type: "directory", name: "mask-border-slice" },
      { type: "directory", name: "mask-border-source" },
      { type: "directory", name: "mask-border-width" },
      { type: "directory", name: "mask-clip" },
      { type: "directory", name: "mask-composite" },
      { type: "directory", name: "mask-image" },
      { type: "directory", name: "mask-mode" },
      { type: "directory", name: "mask-origin" },
      { type: "directory", name: "mask-position" },
      { type: "directory", name: "mask-repeat" },
      { type: "directory", name: "mask-size" },
      { type: "directory", name: "mask-type" },
      { type: "directory", name: "math-depth" },
      { type: "directory", name: "math-shift" },
      { type: "directory", name: "math-style" },
      { type: "directory", name: "max" },
      { type: "directory", name: "max-block-size" },
      { type: "directory", name: "max-content" },
      { type: "directory", name: "max-height" },
      { type: "directory", name: "max-inline-size" },
      { type: "directory", name: "max-width" },
      { type: "directory", name: "min" },
      { type: "directory", name: "min-block-size" },
      { type: "directory", name: "min-content" },
      { type: "directory", name: "min-height" },
      { type: "directory", name: "min-inline-size" },
      { type: "directory", name: "min-width" },
      { type: "directory", name: "minmax" },
      { type: "directory", name: "mix-blend-mode" },
      { type: "directory", name: "mod" },
      { type: "directory", name: "mozilla_extensions" },
      { type: "directory", name: "named-color" },
      { type: "directory", name: "namespace_separator" },
      { type: "directory", name: "nesting_selector" },
      { type: "directory", name: "next-sibling_combinator" },
      { type: "directory", name: "number" },
      { type: "directory", name: "object-fit" },
      { type: "directory", name: "object-position" },
      { type: "directory", name: "offset" },
      { type: "directory", name: "offset-anchor" },
      { type: "directory", name: "offset-distance" },
      { type: "directory", name: "offset-path" },
      { type: "directory", name: "offset-position" },
      { type: "directory", name: "offset-rotate" },
      { type: "directory", name: "opacity" },
      { type: "directory", name: "order" },
      { type: "directory", name: "orphans" },
      { type: "directory", name: "outline" },
      { type: "directory", name: "outline-color" },
      { type: "directory", name: "outline-offset" },
      { type: "directory", name: "outline-style" },
      { type: "directory", name: "outline-width" },
      { type: "directory", name: "overflow" },
      { type: "directory", name: "overflow-anchor" },
      { type: "directory", name: "overflow-block" },
      { type: "directory", name: "overflow-clip-margin" },
      { type: "directory", name: "overflow-inline" },
      { type: "directory", name: "overflow-position" },
      { type: "directory", name: "overflow-wrap" },
      { type: "directory", name: "overflow-x" },
      { type: "directory", name: "overflow-y" },
      { type: "directory", name: "overflow_value" },
      { type: "directory", name: "overlay" },
      { type: "directory", name: "overscroll-behavior" },
      { type: "directory", name: "overscroll-behavior-block" },
      { type: "directory", name: "overscroll-behavior-inline" },
      { type: "directory", name: "overscroll-behavior-x" },
      { type: "directory", name: "overscroll-behavior-y" },
      { type: "directory", name: "padding" },
      { type: "directory", name: "padding-block" },
      { type: "directory", name: "padding-block-end" },
      { type: "directory", name: "padding-block-start" },
      { type: "directory", name: "padding-bottom" },
      { type: "directory", name: "padding-inline" },
      { type: "directory", name: "padding-inline-end" },
      { type: "directory", name: "padding-inline-start" },
      { type: "directory", name: "padding-left" },
      { type: "directory", name: "padding-right" },
      { type: "directory", name: "padding-top" },
      { type: "directory", name: "page" },
      { type: "directory", name: "page-break-after" },
      { type: "directory", name: "page-break-before" },
      { type: "directory", name: "page-break-inside" },
      { type: "directory", name: "paint-order" },
      { type: "directory", name: "percentage" },
      { type: "directory", name: "perspective" },
      { type: "directory", name: "perspective-origin" },
      { type: "directory", name: "place-content" },
      { type: "directory", name: "place-items" },
      { type: "directory", name: "place-self" },
      { type: "directory", name: "pointer-events" },
      { type: "directory", name: "position" },
      { type: "directory", name: "position-anchor" },
      { type: "directory", name: "position-area" },
      { type: "directory", name: "position-area_value" },
      { type: "directory", name: "position-try" },
      { type: "directory", name: "position-try-fallbacks" },
      { type: "directory", name: "position-try-order" },
      { type: "directory", name: "position-visibility" },
      { type: "directory", name: "position_value" },
      { type: "directory", name: "pow" },
      { type: "directory", name: "print-color-adjust" },
      { type: "directory", name: "pseudo-classes" },
      { type: "directory", name: "pseudo-elements" },
      { type: "directory", name: "quotes" },
      { type: "directory", name: "r" },
      { type: "directory", name: "ratio" },
      { type: "directory", name: "ray" },
      { type: "directory", name: "reference" },
      { type: "directory", name: "relative-size" },
      { type: "directory", name: "rem" },
      { type: "directory", name: "repeat" },
      { type: "directory", name: "resize" },
      { type: "directory", name: "resolution" },
      { type: "directory", name: "revert" },
      { type: "directory", name: "revert-layer" },
      { type: "directory", name: "right" },
      { type: "directory", name: "rotate" },
      { type: "directory", name: "round" },
      { type: "directory", name: "row-gap" },
      { type: "directory", name: "ruby-align" },
      { type: "directory", name: "ruby-position" },
      { type: "directory", name: "rx" },
      { type: "directory", name: "ry" },
      { type: "directory", name: "scale" },
      { type: "directory", name: "scroll-behavior" },
      { type: "directory", name: "scroll-margin" },
      { type: "directory", name: "scroll-margin-block" },
      { type: "directory", name: "scroll-margin-block-end" },
      { type: "directory", name: "scroll-margin-block-start" },
      { type: "directory", name: "scroll-margin-bottom" },
      { type: "directory", name: "scroll-margin-inline" },
      { type: "directory", name: "scroll-margin-inline-end" },
      { type: "directory", name: "scroll-margin-inline-start" },
      { type: "directory", name: "scroll-margin-left" },
      { type: "directory", name: "scroll-margin-right" },
      { type: "directory", name: "scroll-margin-top" },
      { type: "directory", name: "scroll-marker-group" },
      { type: "directory", name: "scroll-padding" },
      { type: "directory", name: "scroll-padding-block" },
      { type: "directory", name: "scroll-padding-block-end" },
      { type: "directory", name: "scroll-padding-block-start" },
      { type: "directory", name: "scroll-padding-bottom" },
      { type: "directory", name: "scroll-padding-inline" },
      { type: "directory", name: "scroll-padding-inline-end" },
      { type: "directory", name: "scroll-padding-inline-start" },
      { type: "directory", name: "scroll-padding-left" },
      { type: "directory", name: "scroll-padding-right" },
      { type: "directory", name: "scroll-padding-top" },
      { type: "directory", name: "scroll-snap-align" },
      { type: "directory", name: "scroll-snap-stop" },
      { type: "directory", name: "scroll-snap-type" },
      { type: "directory", name: "scroll-timeline" },
      { type: "directory", name: "scroll-timeline-axis" },
      { type: "directory", name: "scroll-timeline-name" },
      { type: "directory", name: "scrollbar-color" },
      { type: "directory", name: "scrollbar-gutter" },
      { type: "directory", name: "scrollbar-width" },
      { type: "directory", name: "selector_list" },
      { type: "directory", name: "self-position" },
      { type: "directory", name: "shape" },
      { type: "directory", name: "shape-image-threshold" },
      { type: "directory", name: "shape-margin" },
      { type: "directory", name: "shape-outside" },
      { type: "directory", name: "shape-rendering" },
      { type: "directory", name: "sign" },
      { type: "directory", name: "sin" },
      { type: "directory", name: "speak-as" },
      { type: "directory", name: "sqrt" },
      { type: "directory", name: "stop-color" },
      { type: "directory", name: "stop-opacity" },
      { type: "directory", name: "string" },
      { type: "directory", name: "stroke" },
      { type: "directory", name: "stroke-dasharray" },
      { type: "directory", name: "stroke-dashoffset" },
      { type: "directory", name: "stroke-linecap" },
      { type: "directory", name: "stroke-linejoin" },
      { type: "directory", name: "stroke-miterlimit" },
      { type: "directory", name: "stroke-opacity" },
      { type: "directory", name: "stroke-width" },
      { type: "directory", name: "subsequent-sibling_combinator" },
      { type: "directory", name: "symbols" },
      { type: "directory", name: "system-color" },
      { type: "directory", name: "tab-size" },
      { type: "directory", name: "table-layout" },
      { type: "directory", name: "tan" },
      { type: "directory", name: "text-align" },
      { type: "directory", name: "text-align-last" },
      { type: "directory", name: "text-anchor" },
      { type: "directory", name: "text-box" },
      { type: "directory", name: "text-box-edge" },
      { type: "directory", name: "text-box-trim" },
      { type: "directory", name: "text-combine-upright" },
      { type: "directory", name: "text-decoration" },
      { type: "directory", name: "text-decoration-color" },
      { type: "directory", name: "text-decoration-line" },
      { type: "directory", name: "text-decoration-skip" },
      { type: "directory", name: "text-decoration-skip-ink" },
      { type: "directory", name: "text-decoration-style" },
      { type: "directory", name: "text-decoration-thickness" },
      { type: "directory", name: "text-edge" },
      { type: "directory", name: "text-emphasis" },
      { type: "directory", name: "text-emphasis-color" },
      { type: "directory", name: "text-emphasis-position" },
      { type: "directory", name: "text-emphasis-style" },
      { type: "directory", name: "text-indent" },
      { type: "directory", name: "text-justify" },
      { type: "directory", name: "text-orientation" },
      { type: "directory", name: "text-overflow" },
      { type: "directory", name: "text-rendering" },
      { type: "directory", name: "text-shadow" },
      { type: "directory", name: "text-size-adjust" },
      { type: "directory", name: "text-spacing-trim" },
      { type: "directory", name: "text-transform" },
      { type: "directory", name: "text-underline-offset" },
      { type: "directory", name: "text-underline-position" },
      { type: "directory", name: "text-wrap" },
      { type: "directory", name: "text-wrap-mode" },
      { type: "directory", name: "text-wrap-style" },
      { type: "directory", name: "time" },
      { type: "directory", name: "time-percentage" },
      { type: "directory", name: "timeline-scope" },
      { type: "directory", name: "top" },
      { type: "directory", name: "touch-action" },
      { type: "directory", name: "transform" },
      { type: "directory", name: "transform-box" },
      {
        type: "directory",
        name: "transform-function",
        contents: [
          { type: "directory", name: "matrix" },
          { type: "directory", name: "matrix3d" },
          { type: "directory", name: "perspective" },
          { type: "directory", name: "rotate" },
          { type: "directory", name: "rotate3d" },
          { type: "directory", name: "rotatex" },
          { type: "directory", name: "rotatey" },
          { type: "directory", name: "rotatez" },
          { type: "directory", name: "scale" },
          { type: "directory", name: "scale3d" },
          { type: "directory", name: "scalex" },
          { type: "directory", name: "scaley" },
          { type: "directory", name: "scalez" },
          { type: "directory", name: "skew" },
          { type: "directory", name: "skewx" },
          { type: "directory", name: "skewy" },
          { type: "directory", name: "translate" },
          { type: "directory", name: "translate3d" },
          { type: "directory", name: "translatex" },
          { type: "directory", name: "translatey" },
          { type: "directory", name: "translatez" },
        ],
      },
      { type: "directory", name: "transform-origin" },
      { type: "directory", name: "transform-style" },
      { type: "directory", name: "transition" },
      { type: "directory", name: "transition-behavior" },
      { type: "directory", name: "transition-delay" },
      { type: "directory", name: "transition-duration" },
      { type: "directory", name: "transition-property" },
      { type: "directory", name: "transition-timing-function" },
      { type: "directory", name: "translate" },
      { type: "directory", name: "tutorials" },
      { type: "directory", name: "type_selectors" },
      { type: "directory", name: "unicode-bidi" },
      { type: "directory", name: "universal_selectors" },
      { type: "directory", name: "unset" },
      { type: "directory", name: "url_function" },
      { type: "directory", name: "url_value" },
      { type: "directory", name: "user-modify" },
      { type: "directory", name: "user-select" },
      { type: "directory", name: "var" },
      { type: "directory", name: "vector-effect" },
      { type: "directory", name: "vertical-align" },
      { type: "directory", name: "view-timeline" },
      { type: "directory", name: "view-timeline-axis" },
      { type: "directory", name: "view-timeline-inset" },
      { type: "directory", name: "view-timeline-name" },
      { type: "directory", name: "view-transition-name" },
      { type: "directory", name: "visibility" },
      { type: "directory", name: "webkit_extensions" },
      { type: "directory", name: "white-space" },
      { type: "directory", name: "white-space-collapse" },
      { type: "directory", name: "widows" },
      { type: "directory", name: "width" },
      { type: "directory", name: "will-change" },
      { type: "directory", name: "word-break" },
      { type: "directory", name: "word-spacing" },
      { type: "directory", name: "writing-mode" },
      { type: "directory", name: "x" },
      { type: "directory", name: "y" },
      { type: "directory", name: "z-index" },
      { type: "directory", name: "zoom" },
    ],
  },
  { type: "report", directories: 1130 },
];
